truffleuniversity/resources

.github/PULL_REQUEST_TEMPLATE.md
- Adding default `PULL_REQUEST_TEMPLATE.md` and `CODEOWNERS.md` files
~
[Code Owners](https://help.github.com/en/articles/about-code-owners)
[Pull Request Template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository)
=> TU-1:  GitHub templates

docs/resources.mdx
=> Add solidity games to resources

docs/services.mdx
Added Fortmatic to the Wallets section of Services. 
Fortmatic - Build web3 dApps without extensions or downloads.
"Alternative to MetaMask. One SDK to let users interact with your dApp through a beautiful user experience from any browser or device."
https://fortmatic.com/
=> Added Fortmatic to #Wallets

docs/services.mdx
=> test adding a link to ledger

docs/services.mdx
adding a link to W3C DIDs specifications
adding a link to W3C DIDs specifications
=> adding a link to W3C DIDs specifications

docs/resources.mdx, docs/services.mdx
=> A-Z link sorting for resources.mdx and services.mdx

README.md, docs/glossary.mdx
git-0000: Fix readme typo.
Added some items to the glossary.
Fixed a typo in the readme.
N/A
N/A
=> git-0000: Add items to glossary.

docs/resources.mdx
Add books, articles, and courses links to the resources tab.
=> Add Resources

README.md
+ resources link
+ Linke to the google site
=> Added QuickLinks Section / Testing Merge

docs/resources.mdx
=> cryptokitties "link"

docs/resources.mdx
Add articles to the resources section.
=> Add Articles to Resources Tab

docs/introductory.mdx, docs/resources.mdx, docs/services.mdx
=> Various additions (and few small tweaks)

docs/resources.mdx
added a link for a react course
=> added react course link to resources

docs/resources.mdx
https://www.chainshot.com/intro/5c36bf15143eed0017f579755bcdf0c31cf372e860c8b8c6
=> Add vyper tutorial

blog/updates/overview-of-ey-nightfall.md, src/utils/colors.js, src/utils/typography.js
Kevin asked me to publish the blog post here. I suppose this will be the place where everyone else can publish their blog posts as well.
=> Adding new blog post Overview of Nightfall. Previously published on Medium

docs/glossary.mdx, docs/resources.mdx
Adding to glossary and guides.
=> EIP, Keccak256 & Haseeb Q guide

blog/updates/index.md
Add link to tool to convert medium blog posts to markdown to contribution guide.
=> Added info about using medium-2-md

blog/overview-of-ey-nightfall/index.md, blog/truffle-db-faq/index.md
Adding Faina's answers to some questions that came up as part of her Truffle DB session...
=> adding truffle db faq

docs/resources.mdx, docs/services.mdx
Alpha sorting links for clarity and ease of finding.
=> Git 0000 alpha sort

blog/updates/index.md
Local development guidelines for contributing.
=> Local development guidelines

blog/truffle-internals-deep-dive/index.md
Adding the Medium writeup about Truffle internals, from @gnidan talk.
=> Truffle internals blog update

blog/drizzle-whitelist/index.md, docs/index.mdx, docs/introductory.mdx, docs/resources.mdx, doczrc.js, src/components/layout.js, src/utils/colors.js
Sean's awesome Drizzle whitelist addition (as a post)
=> Sean drizzle whitelist

docs/index.mdx, docs/introductory.mdx, docs/resources.mdx, doczrc.js, src/components/layout.js, src/utils/colors.js
=> Visual tweaks

docs/resources.mdx
=> Add UPort/React Truffle Box Tutorial and Quorum Slack Channel

docs/resources.mdx
=> add links to crypto101 and casper paper

docs/resources.mdx
Added a bunch of resources and swapped the order of a few sections.
=> Add to list of resources

docs/resources.mdx
=> Solidity Interview Questions, Dao Hack, and Devcon Links

docs/resources.mdx
=> Add Andreas Antonopoulos resources and Jameson Lopp website

blog/erc777-deep-dive/index.md
Adding my new blog post on ERC777s  to the resources site.
=> Adding new blog post to resources site.

docs/resources.mdx
=> Added articles and guides

docs/resources.mdx
=> Added Misc resources and KeepKey

CONTRIBUTING.md
=> Add All Contributor Bot

docs/glossary.mdx
adding ERC777 to notable token standards and ERC1559 to Notable EIPs.
=> ERC777 + 1559

docs/resources.mdx
=> Add Academic Community resources

docs/resources.mdx
=> Add more resources and fix typo

src/index.mdx
=> fix broken links on introductory page

src/resources.mdx
Wrote an article about how to visualise code coverage of tests in a solidity project
N/A
=> Add link to Code Coverage Article

src/resources.mdx
Added Torus link to resources list under UX section
=> docs: added link to resources

src/defi.mdx, src/index.mdx
=> adding defi theme (more to come)

src/resources.mdx
add some resources related to layer2 solutions
=>  add resources for layer2 solutions

src/resources.mdx
New resource under **Gas and Transaction Execution**:
How nice would be to have a DAPP where the users don't need any tip of wallet to interact with it? There is a solution to there called: Gas Station Network
- https://gsn.openzeppelin.com/
- https://docs.openzeppelin.com/learn/sending-gasless-transactions
=> Add new resource about Gasless Transactions
